alter table BRANCHES ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table COMPONENTS ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table GROUPS ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table GROUP_USER_REF ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table PROPERTIES ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table RANKS ENGINE = InnoDB DEFAULT CHARACTER SET utf8;
alter table SECTIONS ENGINE = InnoDB DEFAULT CHARACTER SET utf8;