CREATE TABLE `BRANCHES` (
  `BRANCH_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `POSITION` int(11) DEFAULT NULL,
  `SECTION_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`BRANCH_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_SECTION` (`SECTION_ID`),
  CONSTRAINT `FK_SECTION` FOREIGN KEY (`SECTION_ID`) REFERENCES `SECTIONS` (`SECTION_ID`)
);

CREATE TABLE `COMPONENTS` (
  `CMP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMPONENT_TYPE` varchar(255) NOT NULL,
  `UUID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `C_TYPE` int(11) DEFAULT NULL,
  PRIMARY KEY (`CMP_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  UNIQUE KEY `NAME` (`NAME`),
  UNIQUE KEY `C_TYPE` (`C_TYPE`)
);

CREATE TABLE `GROUPS` (
  `GROUP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GROUP_ID`),
  UNIQUE KEY `UUID` (`UUID`)
);

CREATE TABLE `GROUP_USER_REF` (
  `GROUP_ID` bigint(20) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  KEY `FK556C5FDF4ECBCAA4` (`USER_ID`),
  KEY `FK556C5FDFB7F395D0` (`GROUP_ID`),
  CONSTRAINT `FK556C5FDF4ECBCAA4` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`),
  CONSTRAINT `FK556C5FDFB7F395D0` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`GROUP_ID`)
);

CREATE TABLE `PROPERTIES` (
  `PROPERTY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `CMP_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PROPERTY_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  KEY `FK_COMPONENT` (`CMP_ID`),
  CONSTRAINT `FK_COMPONENT` FOREIGN KEY (`CMP_ID`) REFERENCES `COMPONENTS` (`CMP_ID`)
);

CREATE TABLE `RANKS` (
  `RANK_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) NOT NULL,
  `RANK_NAME` varchar(255) NOT NULL,
  `AUTO_ASSIGNED` bit(1) DEFAULT NULL,
  `POST_COUNT` int(11) DEFAULT NULL,
  PRIMARY KEY (`RANK_ID`),
  UNIQUE KEY `UUID` (`UUID`),
  UNIQUE KEY `RANK_NAME` (`RANK_NAME`)
);

CREATE TABLE `SECTIONS` (
  `SECTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `POSITION` int(11) DEFAULT NULL,
  `COMPONENT_ID` bigint(20),
  PRIMARY KEY (`SECTION_ID`),
  UNIQUE KEY `UUID` (`UUID`)
);











