ALTER TABLE acl_sid DEFAULT CHARACTER SET utf8;
ALTER TABLE acl_class DEFAULT CHARACTER SET utf8;
ALTER TABLE acl_class MODIFY class VARCHAR(255) CHARACTER SET utf8;
ALTER TABLE acl_entry DEFAULT CHARACTER SET utf8;
ALTER TABLE acl_object_identity DEFAULT CHARACTER SET utf8;